// Compact verb specification list. Expanded into full Verb objects in verbs.ts.
// cat: c = courant, r = régulier, i = irrégulier, x = réfléchi/pronominal
// kind: are | ere | ire | isc | gliere | urre | r-are | r-ere | r-ire | r-isc
// aux:  a = avere (défaut), e = essere

export type SpecKind =
  | "are" | "ere" | "ire" | "isc"
  | "gliere" | "urre"
  | "r-are" | "r-ere" | "r-ire" | "r-isc";

export type SpecOver = Record<string, Record<string, string>>;

export type Spec = [
  string,          // infinitive
  string,          // french
  "c" | "r" | "i" | "x",
  SpecKind,
  ("a" | "e")?,    // auxiliary
  string?,         // irregular past participle
  SpecOver?,       // manual overrides
];

// Verbs derived from an existing irregular model by prefixing every form.
// [infinitive, french, cat, baseInfinitive, prefix, aux, participle?, reflexive?]
export type DerivedSpec = [
  string, string, "c" | "r" | "i" | "x", string, string, "a" | "e", string?, boolean?,
];

export const VERB_SPECS: Spec[] = [
  ["abbracciare", "embrasser / serrer dans ses bras", "r", "are"],
  ["abitare", "habiter", "c", "are"],
  ["abituarsi", "s'habituer", "x", "r-are", "e"],
  ["accadere", "arriver / survenir", "i", "ere", "e", "accaduto", {
    futuro: { io: "accadrò", tu: "accadrai", lui: "accadrà", noi: "accadremo", voi: "accadrete", loro: "accadranno" },
    condizionale: { io: "accadrei", tu: "accadresti", lui: "accadrebbe", noi: "accadremmo", voi: "accadreste", loro: "accadrebbero" },
  }],
  ["accendere", "allumer", "i", "ere", "a", "acceso"],
  ["accettare", "accepter", "r", "are"],
  ["accogliere", "accueillir", "i", "gliere"],
  ["accompagnare", "accompagner", "r", "are"],
  ["accorgersi", "s'apercevoir", "x", "r-ere", "e", "accorto"],
  ["adorare", "adorer", "r", "are"],
  ["affettare", "couper en tranches", "r", "are"],
  ["affittare", "louer", "r", "are"],
  ["agganciare", "accrocher", "r", "are"],
  ["aggiungere", "ajouter", "i", "ere", "a", "aggiunto"],
  ["agire", "agir", "r", "isc"],
  ["aiutare", "aider", "c", "are"],
  ["allacciare", "attacher / lacer", "r", "are"],
  ["allenarsi", "s'entraîner", "x", "r-are", "e"],
  ["allontanarsi", "s'éloigner", "x", "r-are", "e"],
  ["alzare", "lever", "r", "are"],
  ["amare", "aimer", "c", "are"],
  ["ammalarsi", "tomber malade", "x", "r-are", "e"],
  ["ammettere", "admettre", "i", "ere", "a", "ammesso"],
  ["ammirare", "admirer", "r", "are"],
  ["annoiarsi", "s'ennuyer", "x", "r-are", "e"],
  ["annullare", "annuler", "r", "are"],
  ["appendere", "accrocher / suspendre", "i", "ere", "a", "appeso"],
  ["apprezzare", "apprécier", "r", "are"],
  ["approvare", "approuver", "r", "are"],
  ["aprire", "ouvrir", "c", "ire", "a", "aperto"],
  ["arrabbiarsi", "se fâcher", "x", "r-are", "e"],
  ["arredare", "meubler", "r", "are"],
  ["arrendersi", "se rendre", "x", "r-ere", "e", "arreso"],
  ["asciugare", "sécher", "r", "are"],
  ["ascoltare", "écouter", "c", "are"],
  ["aspettare", "attendre", "c", "are"],
  ["assaggiare", "goûter", "r", "are"],
  ["assicurare", "assurer", "r", "are"],
  ["assistere", "assister", "i", "ere", "a", "assistito"],
  ["assumere", "embaucher / assumer", "i", "ere", "a", "assunto"],
  ["attraversare", "traverser", "r", "are"],
  ["aumentare", "augmenter", "r", "are"],
  ["avvertire", "avertir", "r", "ire"],
  ["avvicinarsi", "s'approcher", "x", "r-are", "e"],
  ["avvisare", "prévenir", "r", "are"],
  ["avvitare", "visser", "r", "are"],
  ["baciare", "embrasser", "r", "are"],
  ["bagnarsi", "se mouiller", "x", "r-are", "e"],
  ["ballare", "danser", "r", "are"],
  ["bastare", "suffire", "r", "are", "e"],
  ["bloccare", "bloquer", "r", "are"],
  ["bollire", "bouillir", "r", "ire"],
  ["brindare", "trinquer", "r", "are"],
  ["bruciare", "brûler", "r", "are"],
  ["bussare", "frapper (à la porte)", "r", "are"],
  ["buttare", "jeter", "r", "are"],
  ["cadere", "tomber", "i", "ere", "e", "caduto", {
    futuro: { io: "cadrò", tu: "cadrai", lui: "cadrà", noi: "cadremo", voi: "cadrete", loro: "cadranno" },
    condizionale: { io: "cadrei", tu: "cadresti", lui: "cadrebbe", noi: "cadremmo", voi: "cadreste", loro: "cadrebbero" },
  }],
  ["calcolare", "calculer", "r", "are"],
  ["cambiare", "changer", "r", "are"],
  ["camminare", "marcher", "r", "are"],
  ["cancellare", "effacer", "r", "are"],
  ["capitare", "arriver par hasard", "r", "are", "e"],
  ["caricare", "charger", "r", "are"],
  ["celebrare", "célébrer", "r", "are"],
  ["cenare", "dîner", "r", "are"],
  ["cercare", "chercher", "c", "are"],
  ["chiacchierare", "bavarder", "r", "are"],
  ["chiamare", "appeler", "c", "are"],
  ["chiarire", "éclaircir", "r", "isc"],
  ["chiedere", "demander", "c", "ere", "a", "chiesto"],
  ["chiudere", "fermer", "c", "ere", "a", "chiuso"],
  ["collaborare", "collaborer", "r", "are"],
  ["colpire", "frapper", "r", "isc"],
  ["coltivare", "cultiver", "r", "are"],
  ["cominciare", "commencer", "r", "are"],
  ["comportarsi", "se comporter", "x", "r-are", "e"],
  ["comprare", "acheter", "c", "are"],
  ["comprendere", "comprendre", "i", "ere", "a", "compreso"],
  ["concentrarsi", "se concentrer", "x", "r-are", "e"],
  ["condannare", "condamner", "r", "are"],
  ["condividere", "partager", "i", "ere", "a", "condiviso"],
  ["confermare", "confirmer", "r", "are"],
  ["confondersi", "se tromper / se confondre", "x", "r-ere", "e", "confuso"],
  ["connettere", "connecter", "i", "ere", "a", "connesso"],
  ["conoscere", "connaître", "c", "ere", "a", "conosciuto"],
  ["consegnare", "livrer", "r", "are"],
  ["consigliare", "conseiller", "r", "are"],
  ["consumare", "consommer", "r", "are"],
  ["contare", "compter", "r", "are"],
  ["continuare", "continuer", "r", "are"],
  ["controllare", "contrôler", "r", "are"],
  ["convincere", "convaincre", "i", "ere", "a", "convinto"],
  ["convocare", "convoquer", "r", "are"],
  ["coprire", "couvrir", "i", "ire", "a", "coperto"],
  ["correggere", "corriger", "i", "ere", "a", "corretto"],
  ["correre", "courir", "i", "ere", "a", "corso"],
  ["costare", "coûter", "r", "are", "e"],
  ["costruire", "construire", "r", "isc"],
  ["creare", "créer", "r", "are"],
  ["crescere", "grandir", "i", "ere", "e", "cresciuto"],
  ["cucinare", "cuisiner", "c", "are"],
  ["cuocere", "cuire", "i", "ere", "a", "cotto", {
    presente: { io: "cuocio", tu: "cuoci", lui: "cuoce", noi: "cuociamo", voi: "cuocete", loro: "cuociono" },
    congiuntivo: { io: "cuocia", tu: "cuocia", lui: "cuocia", noi: "cuociamo", voi: "cuociate", loro: "cuociano" },
    imperativo: { tu: "cuoci", noi: "cuociamo", voi: "cuocete" },
  }],
  ["curare", "soigner", "r", "are"],
  ["custodire", "garder / conserver", "r", "isc"],
  ["decidere", "décider", "i", "ere", "a", "deciso"],
  ["deludere", "décevoir", "i", "ere", "a", "deluso"],
  ["descrivere", "décrire", "i", "ere", "a", "descritto"],
  ["desiderare", "désirer", "r", "are"],
  ["difendere", "défendre", "i", "ere", "a", "difeso"],
  ["difendersi", "se défendre", "x", "r-ere", "e", "difeso"],
  ["digerire", "digérer", "r", "isc"],
  ["dimenticare", "oublier", "r", "are"],
  ["diminuire", "diminuer", "r", "isc"],
  ["dimostrare", "démontrer", "r", "are"],
  ["dipendere", "dépendre", "i", "ere", "a", "dipeso"],
  ["dipingere", "peindre", "i", "ere", "a", "dipinto"],
  ["disattivare", "désactiver", "r", "are"],
  ["discutere", "discuter", "i", "ere", "a", "discusso"],
  ["disegnare", "dessiner", "r", "are"],
  ["distruggere", "détruire", "i", "ere", "a", "distrutto"],
  ["diventare", "devenir", "r", "are", "e"],
  ["divertire", "amuser", "r", "ire"],
  ["dividere", "diviser", "i", "ere", "a", "diviso"],
  ["domandare", "demander", "r", "are"],
  ["durare", "durer", "r", "are", "e"],
  ["entrare", "entrer", "c", "are", "e"],
  ["esistere", "exister", "i", "ere", "e", "esistito"],
  ["esprimere", "exprimer", "i", "ere", "a", "espresso"],
  ["evitare", "éviter", "r", "are"],
  ["fatturare", "facturer", "r", "are"],
  ["fermare", "arrêter", "r", "are"],
  ["festeggiare", "fêter", "r", "are"],
  ["fidanzarsi", "se fiancer", "x", "r-are", "e"],
  ["fidarsi", "se fier", "x", "r-are", "e"],
  ["firmare", "signer", "r", "are"],
  ["fissare", "fixer", "r", "are"],
  ["forare", "percer", "r", "are"],
  ["fotografare", "photographier", "r", "are"],
  ["frequentare", "fréquenter", "r", "are"],
  ["friggere", "frire", "i", "ere", "a", "fritto"],
  ["fuggire", "fuir", "r", "ire", "e"],
  ["fumare", "fumer", "r", "are"],
  ["funzionare", "fonctionner", "r", "are"],
  ["garantire", "garantir", "r", "isc"],
  ["giocare", "jouer", "c", "are"],
  ["girare", "tourner", "r", "are"],
  ["grattugiare", "râper", "r", "are"],
  ["gridare", "crier", "r", "are"],
  ["guadagnare", "gagner (de l'argent)", "r", "are"],
  ["guardare", "regarder", "c", "are"],
  ["guarire", "guérir", "r", "isc"],
  ["guidare", "conduire", "r", "are"],
  ["illuminare", "éclairer", "r", "are"],
  ["immaginare", "imaginer", "r", "are"],
  ["imparare", "apprendre", "c", "are"],
  ["incollare", "coller", "r", "are"],
  ["incontrarsi", "se rencontrer", "x", "r-are", "e"],
  ["iniziare", "commencer", "r", "are"],
  ["innamorarsi", "tomber amoureux", "x", "r-are", "e"],
  ["insegnare", "enseigner", "r", "are"],
  ["installare", "installer", "r", "are"],
  ["intendere", "entendre / avoir l'intention", "i", "ere", "a", "inteso"],
  ["interrompere", "interrompre", "i", "ere", "a", "interrotto"],
  ["inviare", "envoyer", "r", "are", "a", undefined, {
    presente: { io: "invio", tu: "invii", lui: "invia", noi: "inviamo", voi: "inviate", loro: "inviano" },
    congiuntivo: { io: "invii", tu: "invii", lui: "invii", noi: "inviamo", voi: "inviate", loro: "inviino" },
  }],
  ["invitare", "inviter", "r", "are"],
  ["lanciare", "lancer", "r", "are"],
  ["lasciare", "laisser", "r", "are"],
  ["lavare", "laver", "c", "are"],
  ["legare", "lier / attacher", "r", "are"],
  ["leggere", "lire", "c", "ere", "a", "letto"],
  ["licenziare", "licencier", "r", "are"],
  ["liquidare", "liquider", "r", "are"],
  ["litigare", "se disputer", "r", "are"],
  ["lottare", "lutter", "r", "are"],
  ["macinare", "moudre", "r", "are"],
  ["mancare", "manquer", "r", "are", "e"],
  ["mandare", "envoyer", "r", "are"],
  ["masticare", "mâcher", "r", "are"],
  ["meritare", "mériter", "r", "are"],
  ["mescolare", "mélanger", "r", "are"],
  ["migliorare", "améliorer", "r", "are"],
  ["misurare", "mesurer", "r", "are"],
  ["mordere", "mordre", "i", "ere", "a", "morso"],
  ["mostrare", "montrer", "r", "are"],
  ["muovere", "bouger / déplacer", "i", "ere", "a", "mosso"],
  ["muoversi", "se déplacer", "x", "r-ere", "e", "mosso"],
  ["nascere", "naître", "i", "ere", "e", "nato"],
  ["nascondere", "cacher", "i", "ere", "a", "nascosto"],
  ["navigare", "naviguer", "r", "are"],
  ["negare", "nier", "r", "are"],
  ["nevicare", "neiger", "r", "are", "e"],
  ["noleggiare", "louer (un véhicule)", "r", "are"],
  ["nominare", "nommer", "r", "are"],
  ["notare", "remarquer", "r", "are"],
  ["nuotare", "nager", "r", "are"],
  ["nutrire", "nourrir", "r", "ire"],
  ["obbligare", "obliger", "r", "are"],
  ["occorrere", "falloir / être nécessaire", "i", "ere", "e", "occorso"],
  ["occupare", "occuper", "r", "are"],
  ["odiare", "haïr / détester", "r", "are"],
  ["offendere", "offenser", "i", "ere", "a", "offeso"],
  ["offrire", "offrir", "i", "ire", "a", "offerto"],
  ["oliare", "huiler", "r", "are"],
  ["ordinare", "commander / ranger", "r", "are"],
  ["organizzare", "organiser", "r", "are"],
  ["ospitare", "héberger", "r", "are"],
  ["ottimizzare", "optimiser", "r", "are"],
  ["pagare", "payer", "c", "are"],
  ["parcheggiare", "garer", "r", "are"],
  ["parere", "sembler / paraître", "i", "ere", "e", "parso", {
    presente: { io: "paio", tu: "pari", lui: "pare", noi: "paiamo", voi: "parete", loro: "paiono" },
    futuro: { io: "parrò", tu: "parrai", lui: "parrà", noi: "parremo", voi: "parrete", loro: "parranno" },
    condizionale: { io: "parrei", tu: "parresti", lui: "parrebbe", noi: "parremmo", voi: "parreste", loro: "parrebbero" },
    congiuntivo: { io: "paia", tu: "paia", lui: "paia", noi: "paiamo", voi: "paiate", loro: "paiano" },
    imperativo: { tu: "", noi: "", voi: "" },
  }],
  ["partecipare", "participer", "r", "are"],
  ["passare", "passer", "r", "are"],
  ["passeggiare", "se promener", "r", "are"],
  ["pattinare", "patiner", "r", "are"],
  ["pedalare", "pédaler", "r", "are"],
  ["pelare", "peler / éplucher", "r", "are"],
  ["pensare", "penser", "c", "are"],
  ["perdere", "perdre", "c", "ere", "a", "perso"],
  ["perdonare", "pardonner", "r", "are"],
  ["permettere", "permettre", "i", "ere", "a", "permesso"],
  ["pesare", "peser", "r", "are"],
  ["piangere", "pleurer", "i", "ere", "a", "pianto"],
  ["piantare", "planter", "r", "are"],
  ["piegare", "plier", "r", "are"],
  ["piovere", "pleuvoir", "i", "ere", "e", "piovuto"],
  ["pitturare", "peindre (un mur)", "r", "are"],
  ["portare", "porter / apporter", "c", "are"],
  ["pranzare", "déjeuner", "r", "are"],
  ["praticare", "pratiquer", "r", "are"],
  ["preferire", "préférer", "r", "isc"],
  ["pregare", "prier", "r", "are"],
  ["premere", "appuyer", "r", "ere"],
  ["prenotare", "réserver", "r", "are"],
  ["preparare", "préparer", "r", "are"],
  ["prepararsi", "se préparer", "x", "r-are", "e"],
  ["prescrivere", "prescrire", "i", "ere", "a", "prescritto"],
  ["presentare", "présenter", "r", "are"],
  ["prestare", "prêter", "r", "are"],
  ["progettare", "concevoir / projeter", "r", "are"],
  ["programmare", "programmer", "r", "are"],
  ["promettere", "promettre", "i", "ere", "a", "promesso"],
  ["promuovere", "promouvoir", "i", "ere", "a", "promosso"],
  ["pronunciare", "prononcer", "r", "are"],
  ["proteggere", "protéger", "i", "ere", "a", "protetto"],
  ["provare", "essayer / prouver", "c", "are"],
  ["provvedere", "pourvoir", "i", "ere", "a", "provvisto"],
  ["pubblicare", "publier", "r", "are"],
  ["pulire", "nettoyer", "r", "isc"],
  ["punire", "punir", "r", "isc"],
  ["raccomandare", "recommander", "r", "are"],
  ["raccontare", "raconter", "r", "are"],
  ["raddoppiare", "doubler", "r", "are"],
  ["radersi", "se raser", "x", "r-ere", "e", "raso"],
  ["radunare", "rassembler", "r", "are"],
  ["raggiungere", "atteindre / rejoindre", "i", "ere", "a", "raggiunto"],
  ["rallentare", "ralentir", "r", "are"],
  ["rapire", "enlever / ravir", "r", "isc"],
  ["reagire", "réagir", "r", "isc"],
  ["recitare", "jouer (un rôle)", "r", "are"],
  ["reclutare", "recruter", "r", "are"],
  ["regalare", "offrir (un cadeau)", "r", "are"],
  ["registrare", "enregistrer", "r", "are"],
  ["regolare", "régler", "r", "are"],
  ["rendere", "rendre", "i", "ere", "a", "reso"],
  ["restare", "rester", "c", "are", "e"],
  ["restituire", "restituer / rendre", "r", "isc"],
  ["revisionare", "réviser", "r", "are"],
  ["riassumere", "résumer", "i", "ere", "a", "riassunto"],
  ["ricevere", "recevoir", "r", "ere"],
  ["riciclare", "recycler", "r", "are"],
  ["riconoscere", "reconnaître", "i", "ere", "a", "riconosciuto"],
  ["ricordare", "se rappeler / rappeler", "c", "are"],
  ["ricucire", "recoudre", "i", "ire", "a", "ricucito", {
    presente: { io: "ricucio", tu: "ricuci", lui: "ricuce", noi: "ricuciamo", voi: "ricucite", loro: "ricuciono" },
    congiuntivo: { io: "ricucia", tu: "ricucia", lui: "ricucia", noi: "ricuciamo", voi: "ricuciate", loro: "ricuciano" },
    imperativo: { tu: "ricuci", noi: "ricuciamo", voi: "ricucite" },
  }],
  ["ridere", "rire", "c", "ere", "a", "riso"],
  ["riempire", "remplir", "i", "ire", "a", "riempito", {
    presente: { io: "riempio", tu: "riempi", lui: "riempie", noi: "riempiamo", voi: "riempite", loro: "riempiono" },
    congiuntivo: { io: "riempia", tu: "riempia", lui: "riempia", noi: "riempiamo", voi: "riempiate", loro: "riempiano" },
    imperativo: { tu: "riempi", noi: "riempiamo", voi: "riempite" },
    gerundio: { lui: "riempiendo" },
  }],
  ["rifiutare", "refuser", "r", "are"],
  ["rifornire", "ravitailler", "r", "isc"],
  ["rilassarsi", "se détendre", "x", "r-are", "e"],
  ["rilevare", "relever / détecter", "r", "are"],
  ["rimandare", "reporter", "r", "are"],
  ["rimborsare", "rembourser", "r", "are"],
  ["rimorchiare", "remorquer", "r", "are"],
  ["ringraziare", "remercier", "r", "are"],
  ["rinnovare", "renouveler", "r", "are"],
  ["rinunciare", "renoncer", "r", "are"],
  ["ripetere", "répéter", "r", "ere"],
  ["riportare", "rapporter", "r", "are"],
  ["riposarsi", "se reposer", "x", "r-are", "e"],
  ["riscaldare", "réchauffer", "r", "are"],
  ["rischiare", "risquer", "r", "are"],
  ["riscuotere", "encaisser", "i", "ere", "a", "riscosso"],
  ["risolvere", "résoudre", "i", "ere", "a", "risolto"],
  ["risparmiare", "épargner", "r", "are"],
  ["rispettare", "respecter", "r", "are"],
  ["rispondere", "répondre", "i", "ere", "a", "risposto"],
  ["risultare", "s'avérer / résulter", "r", "are", "e"],
  ["ritirare", "retirer", "r", "are"],
  ["ritornare", "revenir", "r", "are", "e"],
  ["rompere", "casser", "i", "ere", "a", "rotto"],
  ["rovesciare", "renverser", "r", "are"],
  ["rubare", "voler / dérober", "r", "are"],
  ["ruotare", "faire tourner", "r", "are"],
  ["salare", "saler", "r", "are"],
  ["saldare", "souder / solder", "r", "are"],
  ["saltare", "sauter", "r", "are"],
  ["salutare", "saluer", "r", "are"],
  ["salvare", "sauver", "r", "are"],
  ["sbagliarsi", "se tromper", "x", "r-are", "e"],
  ["sbiancare", "blanchir", "r", "are"],
  ["sbloccare", "débloquer", "r", "are"],
  ["sbottonare", "déboutonner", "r", "are"],
  ["scadere", "expirer / arriver à échéance", "i", "ere", "e", "scaduto", {
    futuro: { io: "scadrò", tu: "scadrai", lui: "scadrà", noi: "scadremo", voi: "scadrete", loro: "scadranno" },
    condizionale: { io: "scadrei", tu: "scadresti", lui: "scadrebbe", noi: "scadremmo", voi: "scadreste", loro: "scadrebbero" },
  }],
  ["scaldare", "chauffer", "r", "are"],
  ["scambiare", "échanger", "r", "are"],
  ["scappare", "s'échapper", "r", "are", "e"],
  ["scaricare", "décharger / télécharger", "r", "are"],
  ["scendere", "descendre", "i", "ere", "e", "sceso"],
  ["scherzare", "plaisanter", "r", "are"],
  ["schiacciare", "écraser", "r", "are"],
  ["schiarire", "éclaircir", "r", "isc"],
  ["scivolare", "glisser", "r", "are", "e"],
  ["scommettere", "parier", "i", "ere", "a", "scommesso"],
  ["sconfiggere", "vaincre", "i", "ere", "a", "sconfitto"],
  ["scontare", "purger / remiser", "r", "are"],
  ["scoprire", "découvrir", "i", "ire", "a", "scoperto"],
  ["scorrere", "s'écouler / défiler", "i", "ere", "e", "scorso"],
  ["scrivere", "écrire", "c", "ere", "a", "scritto"],
  ["scuotere", "secouer", "i", "ere", "a", "scosso"],
  ["scusare", "excuser", "r", "are"],
  ["scusarsi", "s'excuser", "x", "r-are", "e"],
  ["sdraiarsi", "s'allonger", "x", "r-are", "e"],
  ["segare", "scier", "r", "are"],
  ["segnalare", "signaler", "r", "are"],
  ["segnare", "marquer", "r", "are"],
  ["seguire", "suivre", "r", "ire"],
  ["sembrare", "sembler", "r", "are", "e"],
  ["seminare", "semer", "r", "are"],
  ["seppellire", "enterrer", "i", "isc", "a", "sepolto"],
  ["serrare", "serrer / fermer", "r", "are"],
  ["servire", "servir", "r", "ire"],
  ["sfidare", "défier", "r", "are"],
  ["sfogliare", "feuilleter", "r", "are"],
  ["sfruttare", "exploiter", "r", "are"],
  ["sigillare", "sceller", "r", "are"],
  ["smettere", "cesser / arrêter de", "i", "ere", "a", "smesso"],
  ["sminuzzare", "émincer / hacher menu", "r", "are"],
  ["smontare", "démonter", "r", "are"],
  ["soccorrere", "secourir", "i", "ere", "a", "soccorso"],
  ["soffiare", "souffler", "r", "are"],
  ["soffriggere", "faire revenir / rissoler", "i", "ere", "a", "soffritto"],
  ["soffrire", "souffrir", "i", "ire", "a", "sofferto"],
  ["sognare", "rêver", "r", "are"],
  ["sollevare", "soulever", "r", "are"],
  ["sostituire", "remplacer", "r", "isc"],
  ["sottolineare", "souligner", "r", "are"],
  ["sottoscrivere", "souscrire", "i", "ere", "a", "sottoscritto"],
  ["sottrarre", "soustraire", "i", "ere", "a", "sottratto", {
    presente: { io: "sottraggo", tu: "sottrai", lui: "sottrae", noi: "sottraiamo", voi: "sottraete", loro: "sottraggono" },
    imperfetto: { io: "sottraevo", tu: "sottraevi", lui: "sottraeva", noi: "sottraevamo", voi: "sottraevate", loro: "sottraevano" },
    futuro: { io: "sottrarrò", tu: "sottrarrai", lui: "sottrarrà", noi: "sottrarremo", voi: "sottrarrete", loro: "sottrarranno" },
    condizionale: { io: "sottrarrei", tu: "sottrarresti", lui: "sottrarrebbe", noi: "sottrarremmo", voi: "sottrarreste", loro: "sottrarrebbero" },
    congiuntivo: { io: "sottragga", tu: "sottragga", lui: "sottragga", noi: "sottraiamo", voi: "sottraiate", loro: "sottraggano" },
    imperativo: { tu: "sottrai", noi: "sottraiamo", voi: "sottraete" },
    gerundio: { lui: "sottraendo" },
  }],
  ["sovvenzionare", "subventionner", "r", "are"],
  ["spaccare", "fendre / casser", "r", "are"],
  ["spalmare", "étaler / tartiner", "r", "are"],
  ["spandere", "répandre", "i", "ere", "a", "spanto"],
  ["sparire", "disparaître", "r", "isc", "e"],
  ["spaventare", "effrayer", "r", "are"],
  ["spazzare", "balayer", "r", "are"],
  ["spazzolare", "brosser", "r", "are"],
  ["specchiarsi", "se regarder dans la glace", "x", "r-are", "e"],
  ["spedire", "expédier", "r", "isc"],
  ["spendere", "dépenser", "i", "ere", "a", "speso"],
  ["sperare", "espérer", "r", "are"],
  ["spiegare", "expliquer", "r", "are"],
  ["spingere", "pousser", "i", "ere", "a", "spinto"],
  ["spogliare", "déshabiller", "r", "are"],
  ["spogliarsi", "se déshabiller", "x", "r-are", "e"],
  ["spolverare", "épousseter", "r", "are"],
  ["sposarsi", "se marier", "x", "r-are", "e"],
  ["sprecare", "gaspiller", "r", "are"],
  ["spremere", "presser (un fruit)", "r", "ere"],
  ["spruzzare", "vaporiser", "r", "are"],
  ["sputare", "cracher", "r", "are"],
  ["staccare", "détacher", "r", "are"],
  ["stampare", "imprimer", "r", "are"],
  ["stappare", "déboucher", "r", "are"],
  ["stendere", "étendre", "i", "ere", "a", "steso"],
  ["stirare", "repasser", "r", "are"],
  ["strappare", "arracher / déchirer", "r", "are"],
  ["strofinare", "frotter", "r", "are"],
  ["studiare", "étudier", "c", "are"],
  ["subire", "subir", "r", "isc"],
  ["succedere", "arriver / se passer", "i", "ere", "e", "successo"],
  ["succhiare", "sucer", "r", "are"],
  ["sudare", "transpirer", "r", "are"],
  ["suonare", "jouer (d'un instrument)", "r", "are"],
  ["superare", "dépasser", "r", "are"],
  ["svelare", "dévoiler", "r", "are"],
  ["sviluppare", "développer", "r", "are"],
  ["svolgere", "dérouler / effectuer", "i", "ere", "a", "svolto"],
  ["svoltare", "tourner (en voiture)", "r", "are"],
  ["tagliare", "couper", "r", "are"],
  ["telefonare", "téléphoner", "c", "are"],
  ["temere", "craindre", "r", "ere"],
  ["tendere", "tendre", "i", "ere", "a", "teso"],
  ["tentare", "tenter", "r", "are"],
  ["terminare", "terminer", "r", "are"],
  ["tifare", "supporter (une équipe)", "r", "are"],
  ["tingere", "teindre", "i", "ere", "a", "tinto"],
  ["tirare", "tirer", "r", "are"],
  ["toccare", "toucher", "r", "are"],
  ["togliere", "enlever", "i", "gliere"],
  ["tornare", "revenir / rentrer", "c", "are", "e"],
  ["tosare", "tondre", "r", "are"],
  ["tossire", "tousser", "r", "isc"],
  ["tradire", "trahir", "r", "isc"],
  ["trascinare", "traîner", "r", "are"],
  ["trasferire", "transférer", "r", "isc"],
  ["trasformare", "transformer", "r", "are"],
  ["trasmettere", "transmettre", "i", "ere", "a", "trasmesso"],
  ["trasportare", "transporter", "r", "are"],
  ["trattare", "traiter", "r", "are"],
  ["trionfare", "triompher", "r", "are"],
  ["tritare", "hacher", "r", "are"],
  ["trovare", "trouver", "c", "are"],
  ["truccarsi", "se maquiller", "x", "r-are", "e"],
  ["tuffarsi", "plonger", "x", "r-are", "e"],
  ["ubbidire", "obéir", "r", "isc"],
  ["uccidere", "tuer", "i", "ere", "a", "ucciso"],
  ["udire", "entendre / ouïr", "i", "ire", "a", "udito", {
    presente: { io: "odo", tu: "odi", lui: "ode", noi: "udiamo", voi: "udite", loro: "odono" },
    congiuntivo: { io: "oda", tu: "oda", lui: "oda", noi: "udiamo", voi: "udiate", loro: "odano" },
    imperativo: { tu: "odi", noi: "udiamo", voi: "udite" },
  }],
  ["unire", "unir", "r", "isc"],
  ["urlare", "hurler", "r", "are"],
  ["usare", "utiliser", "r", "are"],
  ["usufruire", "bénéficier de", "r", "isc"],
  ["valere", "valoir", "i", "ere", "e", "valso", {
    presente: { io: "valgo", tu: "vali", lui: "vale", noi: "valiamo", voi: "valete", loro: "valgono" },
    futuro: { io: "varrò", tu: "varrai", lui: "varrà", noi: "varremo", voi: "varrete", loro: "varranno" },
    condizionale: { io: "varrei", tu: "varresti", lui: "varrebbe", noi: "varremmo", voi: "varreste", loro: "varrebbero" },
    congiuntivo: { io: "valga", tu: "valga", lui: "valga", noi: "valiamo", voi: "valiate", loro: "valgano" },
    imperativo: { tu: "vali", noi: "valiamo", voi: "valete" },
  }],
  ["valutare", "évaluer", "r", "are"],
  ["vantarsi", "se vanter", "x", "r-are", "e"],
  ["vendicare", "venger", "r", "are"],
  ["vendicarsi", "se venger", "x", "r-are", "e"],
  ["verificare", "vérifier", "r", "are"],
  ["vergognarsi", "avoir honte", "x", "r-are", "e"],
  ["versare", "verser", "r", "are"],
  ["vestire", "habiller", "r", "ire"],
  ["viaggiare", "voyager", "r", "are"],
  ["vietare", "interdire", "r", "are"],
  ["vigilare", "surveiller", "r", "are"],
  ["vincere", "gagner / vaincre", "i", "ere", "a", "vinto"],
  ["visitare", "visiter", "r", "are"],
  ["vivere", "vivre", "c", "ere", "a", "vissuto"],
  ["volare", "voler (dans les airs)", "r", "are"],
  ["volgere", "tourner / diriger", "i", "ere", "a", "volto"],
  ["voltare", "tourner", "r", "are"],
  ["vomitare", "vomir", "r", "are"],
  ["votare", "voter", "r", "are"],
  ["vuotare", "vider", "r", "are"],
];

export const DERIVED_SPECS: DerivedSpec[] = [
  ["appartenere", "appartenir", "i", "tenere", "appar", "e"],
  ["contenere", "contenir", "i", "tenere", "con", "a"],
  ["mantenere", "maintenir", "i", "tenere", "man", "a"],
  ["ottenere", "obtenir", "i", "tenere", "ot", "a"],
  ["ritenere", "estimer / retenir", "i", "tenere", "ri", "a"],
  ["trattenersi", "se retenir / s'attarder", "x", "tenere", "trat", "e", "trattenuto", true],
  ["disporre", "disposer", "i", "porre", "dis", "a", "disposto"],
  ["proporre", "proposer", "i", "porre", "pro", "a", "proposto"],
  ["prevedere", "prévoir", "i", "vedere", "pre", "a", "previsto"],
  ["rivedere", "revoir", "i", "vedere", "ri", "a", "rivisto"],
  ["riuscire", "réussir", "i", "uscire", "ri", "e", "riuscito"],
  ["soddisfare", "satisfaire", "i", "fare", "soddis", "a", "soddisfatto"],
];

// -urre verbs: stem without "urre" (produrre -> "prod")
export const URRE_SPECS: [string, string, "c" | "r" | "i" | "x", string, "a" | "e", string][] = [
  ["produrre", "produire", "i", "prod", "a", "prodotto"],
  ["ridurre", "réduire", "i", "rid", "a", "ridotto"],
];