/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheoryRouteImport } from './routes/theory'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as MistakesRouteImport } from './routes/mistakes'
import { Route as ExerciseRouteImport } from './routes/exercise'
import { Route as DictionaryRouteImport } from './routes/dictionary'
import { Route as IndexRouteImport } from './routes/index'

const TheoryRoute = TheoryRouteImport.update({
  id: '/theory',
  path: '/theory',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const MistakesRoute = MistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciseRoute = ExerciseRouteImport.update({
  id: '/exercise',
  path: '/exercise',
  getParentRoute: () => rootRouteImport,
} as any)
const DictionaryRoute = DictionaryRouteImport.update({
  id: '/dictionary',
  path: '/dictionary',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dictionary': typeof DictionaryRoute
  '/exercise': typeof ExerciseRoute
  '/mistakes': typeof MistakesRoute
  '/stats': typeof StatsRoute
  '/theory': typeof TheoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dictionary': typeof DictionaryRoute
  '/exercise': typeof ExerciseRoute
  '/mistakes': typeof MistakesRoute
  '/stats': typeof StatsRoute
  '/theory': typeof TheoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dictionary': typeof DictionaryRoute
  '/exercise': typeof ExerciseRoute
  '/mistakes': typeof MistakesRoute
  '/stats': typeof StatsRoute
  '/theory': typeof TheoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dictionary'
    | '/exercise'
    | '/mistakes'
    | '/stats'
    | '/theory'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dictionary' | '/exercise' | '/mistakes' | '/stats' | '/theory'
  id:
    | '__root__'
    | '/'
    | '/dictionary'
    | '/exercise'
    | '/mistakes'
    | '/stats'
    | '/theory'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DictionaryRoute: typeof DictionaryRoute
  ExerciseRoute: typeof ExerciseRoute
  MistakesRoute: typeof MistakesRoute
  StatsRoute: typeof StatsRoute
  TheoryRoute: typeof TheoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/theory': {
      id: '/theory'
      path: '/theory'
      fullPath: '/theory'
      preLoaderRoute: typeof TheoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mistakes': {
      id: '/mistakes'
      path: '/mistakes'
      fullPath: '/mistakes'
      preLoaderRoute: typeof MistakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercise': {
      id: '/exercise'
      path: '/exercise'
      fullPath: '/exercise'
      preLoaderRoute: typeof ExerciseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictionary': {
      id: '/dictionary'
      path: '/dictionary'
      fullPath: '/dictionary'
      preLoaderRoute: typeof DictionaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DictionaryRoute: DictionaryRoute,
  ExerciseRoute: ExerciseRoute,
  MistakesRoute: MistakesRoute,
  StatsRoute: StatsRoute,
  TheoryRoute: TheoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
